[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

# RPC endpoints
[rpc_endpoints]
base = "${BASE_RPC_URL}"
scroll = "${SCROLL_RPC_URL}"
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
scroll-sepolia = "${SCROLL_SEPOLIA_RPC_URL}"

# Etherscan API keys
[etherscan]
base = { key = "${BASE_ETHERSCAN_API_KEY}" }
scroll = { key = "${SCROLL_ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
